version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: N01canuse
      MYSQL_DATABASE: book

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # FakeSMTP
  fakesmtp:
    image: djfarrelly/maildev
    ports:
      - "25:25"
    environment:
      - EMAIL_STORAGE=/var/mail

  # Redis

  redis:
    image: redis
    ports:
      - "6379:6379"


#  docker-redis:
#    image: redis:latest
#    restart: always
#    ports:
#      - "6379:6379"


  # Spring Boot Application
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
      - fakesmtp
#      - redis
    links:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: N01canuse
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_OPEN_IN_VIEW: false
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: true
      SPRING_MAIL_HOST: fakesmtp
      SPRING_MAIL_PORT: 25
      SPRING_MAIL_USERNAME: dhruv@gmail.coms
      SPRING_MAIL_PASSWORD: hello
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL: smtp
      SPRING_MAIL_PROPERTIES_MAIL_SMTPS_QUITWAIT: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_PORT: 465
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_CLASS: javax.net.ssl.SSLSocketFactory
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: book-consumer-group
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
      SPRING_PROFILES_ACTIVE: dev
