version: '3'
services:
  rabbitmq:
    image: ${DOCKER_REGISTRY}/jfrog/xray-rabbitmq:3.11.9-management
    container_name: xray_rabbitmq
    hostname: $HOST_ID
    entrypoint: ""
    command: /bin/bash -c " (/setRabbitCluster.sh &) && docker-entrypoint.sh 'rabbitmq-server'"
    ports:
    - ${JF_THIRD_PARTY_BIND_IP}:5672:5672
    - 15672:15672
    - 4369:4369
    - ${JF_THIRD_PARTY_BIND_IP}:25672:25672
    volumes:
    - ${ROOT_DATA_DIR}/xray/app/third-party/rabbitmq/setRabbitCluster.sh:/setRabbitCluster.sh
    - ${ROOT_DATA_DIR}/xray/app/third-party/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    - ${ROOT_DATA_DIR}/xray/var/data/rabbitmq:/var/lib/rabbitmq
    - /etc/localtime:/etc/localtime:ro
    restart: always
    extra_hosts:
    - "${JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME}:${JF_SHARED_RABBITMQ_ACTIVE_NODE_IP}"
    environment:
    - JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME=${JF_SHARED_RABBITMQ_ACTIVE_NODE_NAME}
    - JF_SHARED_RABBITMQ_CLEAN=N # should be in sync with shared.rabbitMq.clean
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
